// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAut15lDYab6zM_B1ZgyaSYCxJIBk_tcIw',
    appId: '1:205225982712:web:783917d0731e45c9de990d',
    messagingSenderId: '205225982712',
    projectId: 'current-quiz-c7954',
    authDomain: 'current-quiz-c7954.firebaseapp.com',
    storageBucket: 'current-quiz-c7954.firebasestorage.app',
    measurementId: 'G-D18B9Q9Y6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCxDCthR63f_TJk506v7eb1Wk47YYFkQs',
    appId: '1:205225982712:android:3604ebff3e20fc70de990d',
    messagingSenderId: '205225982712',
    projectId: 'current-quiz-c7954',
    storageBucket: 'current-quiz-c7954.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Ejnvt3YrgwJ7Yewng1j-PCOwL3uClJk',
    appId: '1:205225982712:ios:8423fd5b7b01fffade990d',
    messagingSenderId: '205225982712',
    projectId: 'current-quiz-c7954',
    storageBucket: 'current-quiz-c7954.firebasestorage.app',
    iosBundleId: 'com.example.myQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Ejnvt3YrgwJ7Yewng1j-PCOwL3uClJk',
    appId: '1:205225982712:ios:8423fd5b7b01fffade990d',
    messagingSenderId: '205225982712',
    projectId: 'current-quiz-c7954',
    storageBucket: 'current-quiz-c7954.firebasestorage.app',
    iosBundleId: 'com.example.myQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAut15lDYab6zM_B1ZgyaSYCxJIBk_tcIw',
    appId: '1:205225982712:web:44d3caf9e7df51e0de990d',
    messagingSenderId: '205225982712',
    projectId: 'current-quiz-c7954',
    authDomain: 'current-quiz-c7954.firebaseapp.com',
    storageBucket: 'current-quiz-c7954.firebasestorage.app',
    measurementId: 'G-EF19CWF66K',
  );

}